### ISSUE TITLE
Enhance the gwdetchar scattering module

### ISSUE THREAD

**Issue by alurban** [gwdetchar/gwdetchar#296]
There's been a lot of work on scattering recently by @andrew-lundgren and @jrsmith02, who have code (based on GWpy) that projects optic motion into _h(t)_ scattering fringes. [**Here**](https://github.com/jrsmith02/ligo-detchar/tree/master/scattering) is one prototype, though @andrew-lundgren has an [**interactive version**](https://git.ligo.org/andrew-lundgren/detchar-notebooks/blob/Local/Local/Scattering/ViewScatter) (requires `LIGO.ORG` credentials) that combines several data streams and plots a spectrogram.

We talked on Slack about migrating this into the `gwdetchar.scattering` module in such a way that you can run it on the command line with `__name__ == __main__`, like so:

```bash
$ python -m gwdetchar.scattering [OPTIONS] ARGUMENTS
```

This would be nice to have for gwdetchar-0.5.0, which will likely be the next release.

**Comment by andrew-lundgren** [comment]
The main things that could improve the code would be:
 1. Better spectrogram, or use Omega scan
 2. Add in other auxiliary channels like angular motion of optics, or motions of ISIs and tables
 3. Maybe a better derivative filter, with a cutoff, if the current one is noisy? I've got a simple one.
 4. And of course a better command-line interface.

**Comment by alurban** [comment]
Thanks @andrew-lundgren, I'm guessing points (2) and (3) also apply to the `gwdetchar-scattering` tool? It's easy to [**add channels**](https://github.com/gwdetchar/gwdetchar/blob/master/gwdetchar/scattering.py#L26-L62), and we can think about improving the derivative filter, which I think right now is just a linear difference between data points.
