### ISSUE TITLE
datafind.get_data frametype issue

### ISSUE THREAD

**Issue by cupidzirconia** [gwdetchar/gwdetchar#413]
I am trying to run io.datafind.get_data for an old time from O3 and am getting a runtime error when I provide a frametype.
`RuntimeError: Missing segments: 
[1268094018 ... 1268178018)`

This is what I ran to get that error.
`channel = 'L1:DMT-SNSW_EFFECTIVE_RANGE_MPC.mean'`
`frametype = 'SenseMonitor_CAL_L1_M'`
`start = 1268094018`
`end = 1268178018`
`ts = get_data(channel, start, end, frametype=frametype)`

If I run the same script without providing the frametype, the command tries to get data from the frames, but fails and retrieves data from NDS successfully. But when I specify the frametype, it does not seem to attempt to get data from NDS after it fails to retrieve data from the frames.

I am also able to run it with a more current time with no issue on the frametype.
`channel = 'L1:DMT-SNSW_EFFECTIVE_RANGE_MPC.mean'`
`frametype = 'SenseMonitor_CAL_L1_M'`
`start = 1338697017`
`end = 1338725932`
`ts2 = get_data(channel, start, end, frametype=frametype)`

**Comment by eagoetz** [comment]
Hi, thanks for your issue. Unfortunately, I am not able to reproduce this.
```
>>> from gwdetchar.io.datafind import get_data
>>> channel = 'L1:DMT-SNSW_EFFECTIVE_RANGE_MPC.mean'
>>> start = 1268094018
>>> end = 1268178018
>>> ts = get_data(channel, start, end)
>>> ts
<TimeSeries([131.04011715, 133.29596066, 132.12451951, ...,
             108.30863351, 131.58357534, 133.35294165]
            unit=Unit("ct"),
            t0=<Quantity 1.268094e+09 s>,
            dt=<Quantity 60. s>,
            name='L1:DMT-SNSW_EFFECTIVE_RANGE_MPC.mean',
            channel=<Channel("L1:DMT-SNSW_EFFECTIVE_RANGE_MPC.mean", 0.016666666666666666 Hz) at 0x7fd581182d60>)>
>>> ts = get_data(channel, start, end, frametype='SenseMonitor_CAL_L1_M')
>>> ts
<TimeSeries([131.04011715, 133.29596066, 132.12451951, ...,
             108.30863351, 131.58357534, 133.35294165]
            unit=Unit("ct"),
            t0=<Quantity 1.268094e+09 s>,
            dt=<Quantity 60. s>,
            name='L1:DMT-SNSW_EFFECTIVE_RANGE_MPC.mean',
            channel=<Channel("L1:DMT-SNSW_EFFECTIVE_RANGE_MPC.mean", 0.016666666666666666 Hz) at 0x7fd57cc1c850>)>
```

So this doesn't seem to be an issue. Perhaps this was not a problem with `gwdetchar.io.datafind.get_data()` but some other problem--maybe even a transient problem? I suggest trying again, use a different cluster, etc.
