### ISSUE TITLE
Rewrite/replace wdq to pythonize omega scans

### ISSUE THREAD

**Issue by alurban** [gwdetchar/gwdetchar#85]
There seems to be a lot of interest in pythonizing omega scans. I think this could be done in a straightforward way using GWPy's [`TimeSeries.q_transform()`](https://gwpy.github.io/docs/stable/examples/timeseries/qscan.html) method along with `gwdetchar.html`, effectively replacing (or rewriting) the functionality currently in `wdq` and `wdq-batch`.

I'm all too happy to make this an O3 development task and try to knock it out before the end of the summer.

**Comment by duncanmmacleod** [comment]
@alurban, this sounds like a great idea, and am happy to help with anything I can. We shouldn't be afraid to throw away any conventions from the MATLAB implementation, including the configuration files, the new code should be written to read from the LIGO-DetChar INI-format channel list files, which are already supported by `gwpy.detector.ChannelList.read`.

**Comment by alurban** [comment]
@duncanmmacleod, fantastic, I'll formally take it on as a project in that case. Please feel free to assign this to me (I don't have master privileges in this repo) and I'll try to have something viable by end-of-summer which can then be reviewed if need be.

And your suggestion sounds very well aligned with what I was thinking!
