### ISSUE TITLE
Huge memory leaks in gwdetchar-omega

### ISSUE THREAD

**Issue by alurban** [gwdetchar/gwdetchar#93]
There are substantial memory leaks in the new `gwdetchar-omega` code:

```
top - 19:17:06 up 83 days, 8 min,  6 users,  load average: 1.41, 0.85, 0.74
Tasks: 1834 total,   3 running, 1826 sleeping,   5 stopped,   0 zombie
%Cpu(s):  6.4 us,  6.7 sy,  0.0 ni, 86.5 id,  0.3 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 13175226+total, 64782468 free, 23777292 used, 43192504 buff/cache
KiB Swap: 16760828 total, 12701648 free,  4059180 used. 10513886+avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                     
2853460 aurban    20   0 6783288   4.5g  27552 R 280.0  3.6   1:02.19 gwdetchar-omega  
```

The code needs to be properly profiled, and these leaks need to be sealed up. For reference, both `dmt_omega` and the Matlab version never use much more than 2 GB per run.

**Comment by areeda** [comment]
We ran multiple Condor on 30 Jul 2018

Log |  Max mem | Run time | Results
-------- | -------- | -------- | --------
[H1-1175884593.625](/home/ldvw/public_html/GWDETCHAR-OMEGA/H1/joseph.areeda/2017-04-10-18.36.16_1175884593.625/job/omega.log) | 75909 MB | 17:38:57 partial | [results](https://ldas-jobs.ligo.caltech.edu/~ldvw/GWDETCHAR-OMEGA/H1/joseph.areeda/2017-04-10-18.36.16_1175884593.625/results/)
[L1-1172489783.070](https://ldas-jobs.ligo.caltech.edu/~ldvw/GWDETCHAR-OMEGA/L1/alexander.urban/2017-03-02-11.36.05_1172489783.070/job/omega.log) | 38560 MB | 8:08:20 | [results](https://ldas-jobs.ligo.caltech.edu/~ldvw/GWDETCHAR-OMEGA/L1/alexander.urban/2017-03-02-11.36.05_1172489783.070/results/)

**Comment by alurban** [comment]
After explicitly closing all plots (#112) and reducing the false alarm rate threshold to 1e-10 Hz, I reran the L1 example above and got nearly a factor of 4 improvement:

Log | Max mem | Run time | Results
-- | -- | -- | --
L1-1172489783.070 | 11289 MB | 01:04:22 | [results](https://ldas-jobs.ligo-la.caltech.edu/~aurban/pyomega-test/L1_1172489783.07/)

This example was made using my local branch for #123, which contains only formatting changes, but includes 3 plots per channel instead of 2.

This is a good start, but per a discussion with @areeda and @duncanmmacleod on Slack, we think we can do better by taking the following steps:

* Use the config file keyword `duration` to determine how much data to read in for each channel block. Right now 512 seconds of data are read in for all channels, whereas, say, only 64 seconds are used to analyze a 16k channel. So this may wind up reducing memory usage by as much as a factor of 512/64 = 8.
* Read in one channel at a time, never cache data outside of the loop in which those data are used. This is more in line with the data processing model used in both the Matlab code and `dmt_omega`.

The second point here will increase runtime, but we hope to alleviate that by introducing multiprocessing.
